version: '3.8'

services:
  app:
    image: python:latest
    container_name: python_app
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "app.py"]
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: Dockerfile



